# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11482ef202c5a0e5896d8124ab13d36d309ee5e213ca80a30b4002ab62f53a980f158726203ef6f4e76957f3072f2c9d17c018656b19d9d6f584c1b9a64b141c

test:
  secret_key_base: f21bc5547635bba7fafa1f63c3668bdbdfbd9bd5da269a9bdc395eac30dd18069eac4812e9e7f23b4c7aef95f5efe6d4be653a9038a1d5a9dac76236d4d7a1ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
